Michaellinaresxk/yacht-puntacana

- components/MainTitle.jsx
adding styles for the main title component
> adding main title component

- components/BoatsComponent.jsx
- components/DestinationsComponent.jsx
- components/buttons/GoingUpButton.jsx
- database/destination.json
- database/destinos.js
- database/yachtsDB.json
- pages/_app.jsx
- pages/destiny.jsx
- pages/index.jsx
fixing issues on going up button and also building the grid of boats
> fixing going button and adding the grid component

- components/Header/DrawerAppBar.jsx
- components/MainBanner.jsx
- components/buttons/BookNowButton.jsx
- pages/_app.jsx
- pages/contact_us.jsx
- pages/destiny.jsx
- pages/index.jsx
- pages/services.jsx
working in some general issues in the home page
> adding general fixings in home page

- components/BoatsComponent.jsx
- components/Footer.jsx
- components/Header/DrawerAppBar.jsx
- components/MainBanner.jsx
- components/MainTitle.jsx
- components/SupportBanner.jsx
- components/VideoComponent.jsx
- components/buttons/SelectLanguageButton.jsx
- package-lock.json
- package.json
- styles/globals.css
several issues on responsive part
> Other fixings

- components/BoatsComponent.jsx
- components/Header/DrawerAppBar.jsx
- components/buttons/SelectLanguageButton.jsx
fixing more issues on responsive
> almost finishing the boat grids

- components/BoatsComponent.jsx
- components/VideoComponent.jsx
- database/boat_data.js
- pages/boat/[id].jsx
- pages/index.jsx
> dynamic fetching of boats already done

- components/BoatsComponent.jsx
- components/VideoComponent.jsx
> new boat card

- components/BoatServices.jsx
- components/BoatsBanner.jsx
- components/BoatsTechnicalData.jsx
- components/DescriptionBoatComponent.jsx
- components/ImageBoatsGallery.jsx
- database/boat_data.js
- next.config.js
- package-lock.json
- package.json
- pages/boat/[id].jsx
> Other boat feching

- components/DescriptionBoatComponent.jsx
- components/Header/DrawerAppBar.jsx
boats description and drawer routing
> adding the boats description and the drawer routing

- components/BoatServices.jsx
the services boat component is already finished
> services boat component finished

- components/BoatServices.jsx
- components/BoatsTechnicalData.jsx
table component almost finished
> Table data boat

- components/BoatsBanner.jsx
- components/Footer.jsx
- components/MainBanner.jsx
- components/SupportBanner.jsx
- components/icons/ContactGroupIcons.jsx
- components/icons/ContactIcons.jsx
> fixing issues on responsive

- components/FormComponent.jsx
- pages/contact_us.jsx
creating the form in the contact page
> adding form component

- components/BannerImageClip.jsx
- components/DescriptionBoatComponent.jsx
- components/Footer.jsx
- components/Header/DrawerAppBar.jsx
- components/icons/ContactGroupIcons.jsx
- components/icons/ContactIcons.jsx
more fixings on responsive and new details
> new things on responsive

- components/FormComponent.jsx
- components/MapComponent.jsx
- package-lock.json
- package.json
- pages/contact_us.jsx
added the email sending message and loading the initial map, but is not finished yet
> adding the email sending option and loading the map

- components/BoatsTechnicalData.jsx
- components/Footer.jsx
- components/Header/DrawerAppBar.jsx
- components/ImageBoatsGallery.jsx
- components/ServicesSliderPalmilla.jsx
- components/ServicesSliderPuntaCana.jsx
- components/ServicesSliderSantaCatalina.jsx
- components/cards/ServicesCard.jsx
- components/cards/TestCard.jsx
- components/video/VideoDesktop.jsx
- next.config.js
- package-lock.json
- package.json
- pages/contact_us.jsx
- pages/destiny.jsx
- pages/index.jsx
- styles/globals.css
- styles/sevices_card.module.css
the destinations page finished
> destiny page

- components/ImageBoatsGallery.jsx
- components/map/ClientMap.jsx
- components/map/Map.jsx
- database/boat_data.js
- package-lock.json
- package.json
- pages/contact_us.jsx
- styles/globals.css
lightbox completely integrated with the boat photo gallery
> gallery with lightbox full integrated

- components/FixedComponent.jsx
- components/FixedComponentImage.jsx
- components/cards/ServicesCard.jsx
- components/map/NewMap.jsx
- pages/_app.jsx
- pages/contact_us.jsx
- pages/services.jsx
- styles/globals.css
> Marker map

- components/BoatsComponent.jsx
- components/FixedComponentImage.jsx
- components/cards/ServicesCard.jsx
- package-lock.json
- package.json
- pages/services.jsx
- styles/globals.css
adding some basic animations with framer motion library just to test and the two fixed background images
> framer, fixed images bacground and some basic animations for test

- components/BoatsBanner.jsx
- components/BoatsComponent.jsx
- components/DestinationsComponent.jsx
- components/Footer.jsx
- components/MainBanner.jsx
- components/ServicesSliderPalmilla.jsx
- components/ServicesSliderPuntaCana.jsx
- components/ServicesSliderSantaCatalina.jsx
- components/SupportBanner.jsx
- components/buttons/BookNowButton.jsx
- components/buttons/GoingUpButton.jsx
- components/buttons/WhatsAppButton.jsx
- components/cards/ServicesCard.jsx
- components/hero/ServicesHero.jsx
- package-lock.json
- package.json
adding basic animation and other few things
> adding basic animations

- components/FormComponent.jsx
- components/MainTitleBoatServices.jsx
- components/ServicesSliderPalmilla.jsx
- components/ServicesSliderPuntaCana.jsx
- components/ServicesSliderSantaCatalina.jsx
- components/buttons/BookNowButton.jsx
- components/hero/ContactHero.jsx
- components/icons/ContactGroupIcons.jsx
- pages/contact_us.jsx
- pages/destiny.jsx
- pages/services.jsx
doing more things on translating the content of the website
> more on tranlation

- components/BoatServices.jsx
- components/BoatsBanner.jsx
- components/BoatsComponent.jsx
- components/BoatsTechnicalData.jsx
- components/ImageBoatsGallery.jsx
- components/boats_description/DescriptionAiconFlyBoat.jsx
- components/boats_description/DescriptionCranchiBoat.jsx
- components/boats_description/DescriptionFairlineBoat.jsx
- components/boats_description/DescriptionMeridianBoat.jsx
- components/boats_description/DescriptionTiara39Boat.jsx
- components/boats_description/DescriptionTiara43Boat.jsx
- pages/boats/aiconfly_boat.jsx
- pages/boats/cranchi_boat.jsx
- pages/boats/fairline_boat.jsx
- pages/boats/meridian_boat.jsx
- pages/boats/tiara39_boat.jsx
- pages/boats/tiara43_boat.jsx
- pages/index.jsx
- public/locales/en/common.json
- public/locales/es/common.json
adding boats card and boats description page translation
> almost finishing translation

- components/Footer.jsx
- components/MainTitle.jsx
- components/buttons/WhatsAppButton.jsx
- components/buttons/debug.log
- components/video/VideoDesktop.jsx
- debug.log
> fixing margins and some other style things in home page

- components/FormComponent.jsx
- components/Header/DrawerAppBar.jsx
- components/buttons/SelectLanguageButton.jsx
- components/debug.log
- components/map/NewMap.jsx
putting the language button active in the mobile view
> refactoring the language button
